version: '3.9'

services:
  backend-fastapi:
    environment: 
      user: postgres
      password: example
      host: ruslan
      port: 5432 
      database: blog
    #image: example/database
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
        - '8000:8000'

  db-for-blogapp:
    image: postgres:16
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
       - /opt/postgres2:/var/lib/postgresql/data/pgdata
       
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata